# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 00:58
from __future__ import unicode_literals

import core.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('source', models.FileField(upload_to=core.models.Multimedia.get_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('source', models.FileField(upload_to=core.models.Multimedia.get_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('lead', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('biography', models.TextField()),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('source', models.FileField(upload_to=core.models.Multimedia.get_upload_to)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='story',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='audio',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
