# Generated by Django 2.2.9 on 2020-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryentrylink',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
