# Generated by Django 2.2.7 on 2020-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20200303_1919"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="linked",
        ),
        migrations.AddField(
            model_name="content",
            name="linked",
            field=models.ManyToManyField(blank=True, to="core.Content"),
        ),
    ]
