# Generated by Django 3.1.1 on 2020-10-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_breaking"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="cover",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.image"
            ),
        ),
        migrations.AlterField(
            model_name="galleryentrylink",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
