# Generated by Django 3.1.1 on 2021-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20201009_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to hide this user from /about/staff",
            ),
        ),
    ]
