# Generated by Django 3.1.1 on 2021-10-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_content",
                to="core.user",
            ),
        ),
    ]
