# Generated by Django 3.1.1 on 2021-10-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_content_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="legacy_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
