# Generated by Django 3.2.8 on 2022-09-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211021_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('source', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.content',),
        ),
    ]
