# Generated by Django 3.2.8 on 2022-09-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_art_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.art'),
        ),
    ]
