# Generated by Django 3.2.8 on 2023-03-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_content_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.section'),
            preserve_default=False,
        ),
    ]
