# Generated by Django 3.2.8 on 2023-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_content_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
