# Generated by Django 3.2.8 on 2023-08-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_section_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='priority',
        ),
    ]
