# Generated by Django 3.2.8 on 2023-09-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_section_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
